# Cloudflare Workers Configuration
# Task Manager API
# NOTE: Only using development environment (task-manager-api-dev)

name = "task-manager-api-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Frontend URL for email links
[vars]
FRONTEND_URL = "https://www.workoto.app"

# Custom domain (must be added via Cloudflare Dashboard):
# Go to: Workers & Pages → task-manager-api-dev → Settings → Domains & Routes
# Add custom domain: api.workoto.app

# Durable Objects
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"
script_name = "task-manager-api-dev"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "task-manager-dev"
database_id = "83af6425-1a63-41f3-a722-46924438e7cc"

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "765c7311eb1a4e05be3ef67cc494bd41"

# Queue Producers
[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-queue-dev"

[[queues.producers]]
binding = "AI_QUEUE"
queue = "ai-queue-dev"

# Queue Consumers
[[queues.consumers]]
queue = "email-queue-dev"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

[[queues.consumers]]
queue = "ai-queue-dev"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 2

# ===================================
# SECRETS (set via: wrangler secret put <NAME>)
# ===================================
# Required secrets:
# - JWT_SECRET (generate with: openssl rand -base64 32)
# - OPENAI_API_KEY
# - SENDGRID_API_KEY
# - RESEND_API_KEY (optional)
